### YamlMime:ModuleUnit
uid: learn.pillars-of-a-great-azure-architecture.3-design-for-security
title: Progettare per la sicurezza
metadata:
  title: Progettare per la sicurezza
  description: Progettare per la sicurezza
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 1b55aacd394eb8f956c0b0ef45713cdcc57a03b0
  ms.sourcegitcommit: b21a4b22de591cfa776684ba2eab9ba27248c65d
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/19/2018
  ms.locfileid: "46354065"
durationInMinutes: 10
content: >
  [!include[](includes/3-design-for-security.md)]
quiz:
  title: Verificare le proprie conoscenze
  questions:
  - content: A quali dei tipi di dati seguenti può essere necessario applicare misure di protezione per la sicurezza?
    choices:
    - content: Dati dei clienti che contengono informazioni personali
      isCorrect: false
      incorrectExplanation: Benché sia importante applicare misure di protezione per la sicurezza appropriate a questi dati, questa non è l'unica scelta corretta.
    - content: Dati finanziari a supporto delle operazioni aziendali
      isCorrect: false
      incorrectExplanation: Benché sia importante applicare a questi dati misure di protezione per la sicurezza appropriate, questa non è l'unica scelta corretta.
    - content: Proprietà intellettuale
      isCorrect: false
      incorrectExplanation: Benché sia importante applicare a questi dati misure di protezione per la sicurezza appropriate, questa non è l'unica scelta corretta.
    - content: A tutti i tipi di dati indicati sopra può essere necessario applicare misure di protezione per la sicurezza
      isCorrect: true
      correctExplanation: Tutti i tipi di dati indicati sopra possono meritare misure di protezione per la sicurezza aggiuntive.
  - content: Quale tra i seguenti è un esempio di attacco che è possibile riscontrare nel livello criteri e accesso?
    choices:
    - content: Credenziali esposte pubblicate online
      isCorrect: true
      correctExplanation: Le credenziali esposte rappresentano un rischio importante per un'organizzazione e sono un attacco del livello criteri e accesso.
    - content: Attacco flood SYN
      isCorrect: false
      incorrectExplanation: Gli attacchi flood SYN sono attacchi di tipo Denial of Service osservati comunemente nel perimetro della rete.
    - content: Seguire un dipendente all'interno di un data center senza presentare credenziali
      isCorrect: false
      incorrectExplanation: Il fatto di seguire un dipendente all'interno di un data Center è un attacco di livello fisico.
    - content: Ransomware che esegue la crittografia dei dischi di una macchina virtuale
      isCorrect: false
      incorrectExplanation: Gli attacchi tramite ransomware sono attacchi del livello di calcolo/della macchina virtuale.
