### YamlMime:ModuleUnit
uid: learn.pillars-of-a-great-azure-architecture.3-design-for-security
title: Progettare per la sicurezza
metadata:
  title: Progettare per la sicurezza
  description: Progettare per la sicurezza
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: b1f1fd5afaa153340eee740bd0071fc8295c63e6
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44245716"
durationInMinutes: 10
content: >
  [!include[](includes/3-design-for-security.md)]
quiz:
  title: 'Verifica delle conoscenze: Progettare per la sicurezza'
  questions:
  - content: A quali dei tipi seguenti di dati può essere necessario applicare misure di protezione per la sicurezza?
    choices:
    - content: Dati dei clienti che contengono informazioni personali
      isCorrect: false
      incorrectExplanation: Benché sia importante applicare misure di protezione per la sicurezza appropriate a questi dati, questa non è l'unica scelta corretta.
    - content: Dati finanziari a supporto delle operazioni aziendali
      isCorrect: false
      incorrectExplanation: Benché sia importante applicare misure di protezione per la sicurezza appropriate a questi dati, questa non è l'unica scelta corretta.
    - content: Dati contenenti proprietà intellettuale
      isCorrect: false
      incorrectExplanation: Benché sia importante applicare misure di protezione per la sicurezza appropriate a questi dati, questa non è l'unica scelta corretta.
    - content: A tutti i tipi di dati indicati sopra può essere necessario applicare misure di protezione per la sicurezza
      isCorrect: true
      correctExplanation: Tutti i tipi di dati indicati sopra possono meritare misure di protezione per la sicurezza aggiuntive.
  - content: Quale tra i seguenti è un esempio di attacco che è possibile riscontrare nel livello perimetrale?
    choices:
    - content: Credenziali esposte pubblicate online
      isCorrect: false
      incorrectExplanation: Le credenziali esposte pongono un rischio elevato per un'organizzazione, ma non costituiscono un attacco del livello perimetrale.
    - content: Attacco flood SYN
      isCorrect: true
      correctExplanation: Gli attacchi flood SYN sono un tipo di attacco Denial of Service osservato comunemente nella rete perimetrale.
    - content: Progettazione di ingressi per penetrare nel data center
      isCorrect: false
      incorrectExplanation: La progettazione di ingressi è un attacco del livello fisico.
    - content: Ransomware per la crittografia dei dischi di una macchina virtuale
      isCorrect: false
      incorrectExplanation: Gli attacchi tramite ransomware sono attacchi del livello di calcolo/della macchina virtuale.
