### YamlMime:ModuleUnit
uid: learn.scale-and-size-virtual-machines.5-exercise-create-a-scale-set-and-configure-autoscaling
title: 'Esercizio: creare un set di scalabilità e configurare la scalabilità automatica'
metadata:
  title: 'Esercizio: creare un set di scalabilità e configurare la scalabilità automatica'
  description: 'Esercizio: creare un set di scalabilità e configurare la scalabilità automatica'
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 10
content: |
  [!include[](includes/5-exercise-create-a-scale-set-and-configure-autoscaling.md)]