### YamlMime:ModuleUnit
uid: learn.scale-and-size-virtual-machines.5-exercise-create-a-scale-set-and-configure-autoscaling
title: <span data-ttu-id="f9f9a-101">Esercizio - Creare un set di scalabilità e configurare la scalabilità automatica</span><span class="sxs-lookup"><span data-stu-id="f9f9a-101">Exercise - Create a scale set and configure autoscaling</span></span>
metadata:
  title: <span data-ttu-id="f9f9a-102">Esercizio - Creare un set di scalabilità e configurare la scalabilità automatica</span><span class="sxs-lookup"><span data-stu-id="f9f9a-102">Exercise - Create a scale set and configure autoscaling</span></span>
  description: <span data-ttu-id="f9f9a-103">Esercizio - Creare un set di scalabilità e configurare la scalabilità automatica</span><span class="sxs-lookup"><span data-stu-id="f9f9a-103">Exercise - Create a scale set and configure autoscaling</span></span>
  ms.openlocfilehash: ca265df828582f0b74003b36a4e33b824a111290
  ms.sourcegitcommit: 4d2d6d8c52fa24ae1c5c06cf4cb3afa09d8c8363
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44254820"
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-a-scale-set-and-configure-autoscaling.md)]'
