### YamlMime:ModuleUnit
uid: learn.enable-reliable-messaging-for-big-data-applications-using-azure-event-hubs.5-exercise-configure-applications-to-send-or-receive-messages-through-an-event-hub
title: <span data-ttu-id="23b3a-101">Configurare le applicazioni per l'invio o la ricezione dei messaggi tramite un hub eventi</span><span class="sxs-lookup"><span data-stu-id="23b3a-101">Configure applications to send or receive messages through an Event Hub</span></span>
metadata:
  title: <span data-ttu-id="23b3a-102">Configurare le applicazioni per l'invio o la ricezione dei messaggi tramite un hub eventi</span><span class="sxs-lookup"><span data-stu-id="23b3a-102">Configure applications to send or receive messages through an Event Hub</span></span>
  description: <span data-ttu-id="23b3a-103">Configurare le applicazioni per l'invio o la ricezione dei messaggi tramite un hub eventi</span><span class="sxs-lookup"><span data-stu-id="23b3a-103">Configure applications to send or receive messages through an Event Hub</span></span>
  ms.openlocfilehash: 28d21d21388a71eea65893daeb7f6d2a374c8e64
  ms.sourcegitcommit: 314b617e66d461bd6bf5aa076aacdc150b773606
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/06/2018
  ms.locfileid: "43833702"
durationInMinutes: 10
content: '[!include[](includes/5-exercise-configure-applications-to-send-or-receive-messages-through-an-event-hub.md)]'
