### YamlMime:ModuleUnit
uid: learn.enable-reliable-messaging-for-big-data-applications-using-azure-event-hubs.5-exercise-configure-applications-to-send-or-receive-messages-through-an-event-hub
title: "<span data-ttu-id=\"e25ff-101\">Esercizio: configurare le applicazioni per l'invio o la ricezione dei messaggi tramite un hub eventi</span><span class=\"sxs-lookup\"><span data-stu-id=\"e25ff-101\">Exercise - Configure applications to send or receive messages through an Event Hub</span></span>"
metadata:
  title: "<span data-ttu-id=\"e25ff-102\">Esercizio: configurare le applicazioni per l'invio o la ricezione dei messaggi tramite un hub eventi</span><span class=\"sxs-lookup\"><span data-stu-id=\"e25ff-102\">Exercise - Configure applications to send or receive messages through an Event Hub</span></span>"
  description: <span data-ttu-id="e25ff-103">Configurare le applicazioni per l'invio o la ricezione dei messaggi tramite un hub eventi</span><span class="sxs-lookup"><span data-stu-id="e25ff-103">Configure applications to send or receive messages through an Event Hub</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: de40d61e225340c649c9efec1ac10093508b9459
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47133812"
interactive: bash
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/5-exercise-configure-applications-to-send-or-receive-messages-through-an-event-hub.md)]'
