### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.3-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal
title: Abilitare e configurare la cache disco macchina virtuale di Azure usando il portale di Azure
metadata:
  title: Abilitare e configurare la cache disco macchina virtuale di Azure usando il portale di Azure
  description: Abilitare e configurare la cache disco macchina virtuale di Azure usando il portale di Azure
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 5
content: |
  [!include[](includes/3-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal.md)