### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.3-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal
title: Abilitare e configurare la cache del disco delle macchine virtuali di Azure tramite il portale di Azure
metadata:
  title: Abilitare e configurare la cache del disco delle macchine virtuali di Azure tramite il portale di Azure
  description: Abilitare e configurare la cache del disco delle macchine virtuali di Azure tramite il portale di Azure
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 20238bbb5638ea2e5985a7a51e5885700f64099b
  ms.sourcegitcommit: b21a4b22de591cfa776684ba2eab9ba27248c65d
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/19/2018
  ms.locfileid: "46343210"
durationInMinutes: 5
content: '[!include[](includes/3-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal.md)'
