### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.4-exercise-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal
title: <span data-ttu-id="e9937-101">Esercizio - Abilitare e configurare la cache del disco delle macchine virtuali di Azure tramite il portale di Azure</span><span class="sxs-lookup"><span data-stu-id="e9937-101">Exercise - Enable and configure Azure VM disk cache with the Azure portal</span></span>
metadata:
  title: <span data-ttu-id="e9937-102">Esercizio - Abilitare e configurare la cache del disco delle macchine virtuali di Azure tramite il portale di Azure</span><span class="sxs-lookup"><span data-stu-id="e9937-102">Exercise - Enable and configure Azure VM disk cache with the Azure portal</span></span>
  description: <span data-ttu-id="e9937-103">Esercizio - Abilitare e configurare la cache del disco delle macchine virtuali di Azure tramite il portale di Azure</span><span class="sxs-lookup"><span data-stu-id="e9937-103">Exercise - Enable and configure Azure VM disk cache with the Azure portal</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 85d7905334c09c828dea8329dcc00f3f72ffa6d3
  ms.sourcegitcommit: b21a4b22de591cfa776684ba2eab9ba27248c65d
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/19/2018
  ms.locfileid: "46341123"
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/4-exercise-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal.md)]'
