### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.4-exercise-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal
title: Esercizio - Abilitare e configurare la cache del disco delle macchine virtuali di Azure tramite il portale di Azure
metadata:
  title: Esercizio - Abilitare e configurare la cache del disco delle macchine virtuali di Azure tramite il portale di Azure
  description: Esercizio - Abilitare e configurare la cache del disco delle macchine virtuali di Azure tramite il portale di Azure
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 1c1727360758d4bf4b9835de212fe5775cb9a5db
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44233119"
durationInMinutes: 10
content: '[!include[](includes/4-exercise-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal.md)]'
