### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.4-exercise-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal
title: <span data-ttu-id="863a2-101">Esercizio - Abilitare e configurare la cache del disco delle macchine virtuali di Azure tramite il portale di Azure</span><span class="sxs-lookup"><span data-stu-id="863a2-101">Exercise - Enable and configure Azure VM disk cache with the Azure portal</span></span>
metadata:
  title: <span data-ttu-id="863a2-102">Esercizio - Abilitare e configurare la cache del disco delle macchine virtuali di Azure tramite il portale di Azure</span><span class="sxs-lookup"><span data-stu-id="863a2-102">Exercise - Enable and configure Azure VM disk cache with the Azure portal</span></span>
  description: <span data-ttu-id="863a2-103">Esercizio - Abilitare e configurare la cache del disco delle macchine virtuali di Azure tramite il portale di Azure</span><span class="sxs-lookup"><span data-stu-id="863a2-103">Exercise - Enable and configure Azure VM disk cache with the Azure portal</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 85d7905334c09c828dea8329dcc00f3f72ffa6d3
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47134946"
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/4-exercise-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal.md)]'
