### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.6-exercise-manage-cache-settings-with-powershell
title: 'Esercizio: gestire le impostazioni della cache con PowerShell'
metadata:
  title: 'Esercizio: gestire le impostazioni della cache con PowerShell'
  description: 'Esercizio: gestire le impostazioni della cache con PowerShell'
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
interactive: powershell
azureSandbox: true
durationInMinutes: 10
content: |
  [!include[](includes/6-exercise-manage-cache-settings-with-powershell.md)]