### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.7-exercise-add-azure-storage-configuration-to-your-app
title: Aggiungere la configurazione di Archiviazione di Azure all'app
metadata:
  title: Aggiungere la configurazione di Archiviazione di Azure all'app
  description: Aggiungere la configurazione di Archiviazione di Azure all'app
  ms.openlocfilehash: e152336211d9a6d9e37f9443e94712e5afac3722
  ms.sourcegitcommit: e90461bc6f88bca3b53183b476553633f93990a3
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/06/2018
  ms.locfileid: "44043288"
durationInMinutes: 10
content: '[!include[](includes/7-exercise-add-azure-storage-configuration-to-your-app.md)]'
