### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.7-exercise-add-azure-storage-configuration-to-your-app
title: <span data-ttu-id="424b2-101">Esercizio - Aggiungere la configurazione dell'Archiviazione di Azure all'app</span><span class="sxs-lookup"><span data-stu-id="424b2-101">Exercise - Add Azure Storage configuration to your app</span></span>
metadata:
  title: <span data-ttu-id="424b2-102">Esercizio - Aggiungere la configurazione dell'Archiviazione di Azure all'app</span><span class="sxs-lookup"><span data-stu-id="424b2-102">Exercise - Add Azure Storage configuration to your app</span></span>
  description: <span data-ttu-id="424b2-103">Esercizio - Aggiungere la configurazione dell'Archiviazione di Azure all'app</span><span class="sxs-lookup"><span data-stu-id="424b2-103">Exercise - Add Azure Storage configuration to your app</span></span>
  ms.openlocfilehash: 81492226750978399fb2a82fb32c14b5ddefb08d
  ms.sourcegitcommit: 107578417899e44b5611917dec7bcc21d4c1582e
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 08/29/2018
  ms.locfileid: "43228207"
durationInMinutes: 10
content: '[!include[](includes/7-exercise-add-azure-storage-configuration-to-your-app.md)]'
