### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.8-exercise-add-azure-storage-configuration-to-your-app
title: <span data-ttu-id="943c3-101">Aggiungere la configurazione di Archiviazione di Azure all'app</span><span class="sxs-lookup"><span data-stu-id="943c3-101">Add Azure Storage configuration to your app</span></span>
metadata:
  title: <span data-ttu-id="943c3-102">Aggiungere la configurazione di Archiviazione di Azure all'app</span><span class="sxs-lookup"><span data-stu-id="943c3-102">Add Azure Storage configuration to your app</span></span>
  description: <span data-ttu-id="943c3-103">Aggiungere la configurazione di Archiviazione di Azure all'app</span><span class="sxs-lookup"><span data-stu-id="943c3-103">Add Azure Storage configuration to your app</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  zone_pivot_groups: dev-lang-csharp-javascript
  ms.openlocfilehash: 9ed11b520e16ccaf47e786ff5a63272921f4bf90
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47131869"
interactive: bash-editor
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/8-exercise-add-azure-storage-configuration-to-your-app.md)]'
