### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.9-exercise-connect-with-your-azure-storage-configuration
title: Connettersi con la configurazione di Archiviazione di Azure
metadata:
  title: Connettersi con la configurazione di Archiviazione di Azure
  description: Connettersi con la configurazione di Archiviazione di Azure
  ms.openlocfilehash: d751f669ef3861a64abfdd02301aa7e79edb9c12
  ms.sourcegitcommit: e90461bc6f88bca3b53183b476553633f93990a3
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/06/2018
  ms.locfileid: "44043781"
durationInMinutes: 10
content: '[!include[](includes/9-exercise-connect-with-your-azure-storage-configuration.md)]'
