### YamlMime:ModuleUnit
uid: learn.manage-secrets-with-azure-key-vault.6-configure-deploy-run-azure
title: <span data-ttu-id="cc554-101">Configurare, distribuire ed eseguire su Azure</span><span class="sxs-lookup"><span data-stu-id="cc554-101">Configure, deploy, and run in Azure</span></span>
metadata:
  title: <span data-ttu-id="cc554-102">Configurare, distribuire ed eseguire su Azure</span><span class="sxs-lookup"><span data-stu-id="cc554-102">Configure, deploy, and run in Azure</span></span>
  description: <span data-ttu-id="cc554-103">Configurare, distribuire ed eseguire su Azure</span><span class="sxs-lookup"><span data-stu-id="cc554-103">Configure, deploy, and run in Azure</span></span>
  ms.openlocfilehash: 2877e343b38fce7016c15621f390db6343838e7d
  ms.sourcegitcommit: 12b4711682dac42f742a944fd9baa0e9dd09cf35
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 08/22/2018
  ms.locfileid: "40443151"
durationInMinutes: 10
interactive: bash
content: '[!include[](includes/6-configure-deploy-run-azure.md)]'
