### YamlMime:ModuleUnit
uid: learn.intro-to-containers.2-configure-local
metadata:
  title: Configurare un ambiente di sviluppo del contenitore locale
  description: Configurare un ambiente di sviluppo del contenitore locale.
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
title: Configurare un ambiente di sviluppo del contenitore locale
durationInMinutes: 10
content: |
  [!include[](includes/2-configure-local.md)]