### YamlMime:ModuleUnit
uid: learn.design-for-performance-and-scalability.5-identify-performance-bottlenecks-in-your-application
title: Identificare i colli di bottiglia relativi alle prestazioni nell'applicazione
metadata:
  title: Identificare i colli di bottiglia relativi alle prestazioni nell'applicazione
  description: In questa unità viene spiegato come identificare i colli di bottiglia relativi alle prestazioni nell'applicazione
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 5
content: |
  [!include[](includes/5-identify-performance-bottlenecks-in-your-application.md)]
quiz:
  title: 'Verifica delle conoscenze: identificare i colli di bottiglia relativi alle prestazioni nell''applicazione'
  questions:
    - content: Quale delle seguenti affermazioni meglio descrive Application Insights?
      choices:
        - content: Un'unica console per le esigenze di monitoraggio in Azure
          isCorrect: false
          incorrectExplanation: 'Application Insights può fornire un''ampia gamma di dati sulle prestazioni delle applicazioni, ma non costituisce una soluzione di monitoraggio completa di Azure.'
        - content: Un'implementazione del modello di monitoraggio dell'integrità dell'endpoint
          isCorrect: false
          incorrectExplanation: Il modello di monitoraggio dell'integrità dell'endpoint è incentrato sul monitoraggio degli endpoint esposti dall'applicazione per l'integrità complessiva.
        - content: Un'area di lavoro per abilitare la raccolta dei log tra applicazioni e infrastruttura
          isCorrect: false
          incorrectExplanation: Log Analytics è un'area di lavoro che abilita la raccolta dei log tra applicazioni e infrastruttura.
        - content: 'Un servizio per monitorare la disponibilità, le prestazioni e l''uso delle applicazioni Web'
          isCorrect: true
          correctExplanation: 'Application Insights è un servizio per monitorare la disponibilità, le prestazioni e l''uso delle applicazioni Web.'
    - content: È possibile usare Log Analytics per tenere traccia delle metriche e dei log personalizzati.
      choices:
        - content: Vero
          isCorrect: true
          correctExplanation: Per le metriche e i log personalizzati è possibile usare l'API di raccolta dati HTTP per scrivere dati in Log Analytics da qualsiasi client dell'API REST oppure un'app per la logica di Azure per scrivere i dati di un flusso di lavoro personalizzato.
        - content: Falso
          isCorrect: false
          incorrectExplanation: Per le metriche e i log personalizzati è possibile usare l'API di raccolta dati HTTP per scrivere dati in Log Analytics da qualsiasi client dell'API REST oppure un'app per la logica di Azure per scrivere i dati di un flusso di lavoro personalizzato.