### YamlMime:ModuleUnit
uid: learn.optimize-web-app-with-redis.3-configure-redis-cache
title: Configurare la Cache Redis
metadata:
  title: Configurare la Cache Redis
  description: Configurare la Cache Redis
  ms.openlocfilehash: 97146e54b1e46659f765149a3199b57701933a2b
  ms.sourcegitcommit: bf091e3a389138b59573865ca54775e38a4ffa1f
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 08/29/2018
  ms.locfileid: "43154661"
durationInMinutes: 5
content: '[!include[](includes/3-configure-redis-cache.md)]'
