### YamlMime:ModuleUnit
uid: learn.introduction-to-security.5-network-security
title: Proteggere la rete
metadata:
  title: Proteggere la rete
  description: In questa unità viene spiegato come proteggere l'infrastruttura di rete.
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 434584c1861f5b8031069c787b878c654a8ba848
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47137127"
durationInMinutes: 5
content: '[!include[](includes/5-network-security.md)]'
