### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-web-apps.5-exercise-create-an-asp.net-core-web-application-on-linux
title: "Esercizio: Creare un'applicazione ASP.NET Core in Linux"
metadata:
  title: "Esercizio: Creare un'applicazione ASP.NET Core in Linux"
  description: "Esercizio: Creare un'applicazione ASP.NET Core in Linux"
  ms.openlocfilehash: 1205619f0129555a08587fa142627e6d917e3fcb
  ms.sourcegitcommit: a8497a897faccb27bfeaf5812a5887ac15f97625
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 08/24/2018
  ms.locfileid: "42821990"
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-an-asp.net-core-web-application-on-linux.md)]'
