### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-web-apps.5-exercise-create-an-asp.net-core-web-application-on-linux
title: "<span data-ttu-id=\"71db7-101\">Esercizio: Creare un'applicazione ASP.NET Core in Linux</span><span class=\"sxs-lookup\"><span data-stu-id=\"71db7-101\">Exercise - Create an ASP.NET Core application on Linux</span></span>"
metadata:
  title: "<span data-ttu-id=\"71db7-102\">Esercizio: Creare un'applicazione ASP.NET Core in Linux</span><span class=\"sxs-lookup\"><span data-stu-id=\"71db7-102\">Exercise - Create an ASP.NET Core application on Linux</span></span>"
  description: "<span data-ttu-id=\"71db7-103\">Esercizio: Creare un'applicazione ASP.NET Core in Linux</span><span class=\"sxs-lookup\"><span data-stu-id=\"71db7-103\">Exercise - Create an ASP.NET Core application on Linux</span></span>"
  ms.openlocfilehash: 1205619f0129555a08587fa142627e6d917e3fcb
  ms.sourcegitcommit: 7cb102aab9e02ef52429d61a119a574c7ad3b2fb
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43725512"
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-an-asp.net-core-web-application-on-linux.md)]'
