### YamlMime:ModuleUnit
uid: learn.interactive-deep-learning.4-configure-dsvm
title: Configurare la DSVM
metadata:
  title: Configurare la Data Science Virtual Machine per l'apprendimento profondo
  description: Configurare la Data Science Virtual Machine per l'apprendimento profondo
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: e7beee6bf1a56df0378cba82b042d506589f361d
  ms.sourcegitcommit: 8213d1af6ad9da967a5e195f0b40b00265cb192c
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/10/2018
  ms.locfileid: "44309338"
interactive: bash
azureSandbox: true
durationInMinutes: 30
content: '[!include[](includes/4-configure-dsvm.md)]'
