### YamlMime:ModuleUnit
uid: learn.interactive-deep-learning.4-configure-dsvm
title: Configurare la DSVM
metadata:
  title: Configurare la Data Science Virtual Machine per l'apprendimento profondo
  description: Configurare la Data Science Virtual Machine per l'apprendimento profondo
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 817429ab3de31e91be6c9d471a03a8f9c0f0ec85
  ms.sourcegitcommit: 1c45ea8b740761474e8cb320f14c88ae71a13261
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/11/2018
  ms.locfileid: "44383634"
labId: 45998
interactive: bash
azureSandbox: true
durationInMinutes: 30
content: '[!include[](includes/4-configure-dsvm.md)]'
