### YamlMime:ModuleUnit
uid: learn.interactive-deep-learning.4-configure-dsvm
title: Configurare la DSVM
metadata:
  title: Configurare la Data Science Virtual Machine per l'apprendimento profondo
  description: Configurare la Data Science Virtual Machine per l'apprendimento profondo
  ms.openlocfilehash: 54f188e18c055a9d80f3a71bf482a781b723b1e2
  ms.sourcegitcommit: 314b617e66d461bd6bf5aa076aacdc150b773606
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/06/2018
  ms.locfileid: "43833171"
interactive: bash
durationInMinutes: 30
content: '[!include[](includes/4-configure-dsvm.md)]'
