### YamlMime:ModuleUnit
uid: learn.interactive-deep-learning.4-configure-dsvm
title: Configurare la DSVM
metadata:
  title: Configurare la Data Science Virtual Machine per l'apprendimento profondo
  description: Configurare la Data Science Virtual Machine per l'apprendimento profondo
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
labId: 45998
interactive: bash
azureSandbox: true
durationInMinutes: 30
content: |
  [!include[](includes/4-configure-dsvm.md)]