### YamlMime:ModuleUnit
uid: learn.run-docker-containers-aci.4-use-environment-variables
metadata:
  title: Impostare le variabili di ambiente
  description: Impostare le variabili di ambiente in Istanze di contenitore di Azure.
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
title: Impostare le variabili di ambiente
interactive: bash
azureSandbox: true
durationInMinutes: 10
content: |
  [!include[](includes/4-use-environment-variables.md)]