### YamlMime:ModuleUnit
uid: learn.run-docker-containers-aci.4-use-environment-variables
interactive: bash
metadata:
  title: Impostare le variabili di ambiente
  description: Impostare le variabili di ambiente in Istanze di contenitore di Azure.
  ms.openlocfilehash: 921168a568e52b47ff347521fff4969213d0fa88
  ms.sourcegitcommit: 314b617e66d461bd6bf5aa076aacdc150b773606
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/06/2018
  ms.locfileid: "43833786"
title: Impostare le variabili di ambiente
durationInMinutes: 10
content: '[!include[](includes/4-use-environment-variables.md)]'
