### YamlMime:ModuleUnit
uid: learn.secure-your-azure-virtual-machine-disks.6-exercise-automate-secure-vm-deployments-using-arm-templates
title: <span data-ttu-id="0e274-101">Esercizio - Automatizzare le distribuzioni di VM sicure aggiungendo la crittografia ai modelli di Azure Resource Manager</span><span class="sxs-lookup"><span data-stu-id="0e274-101">Exercise - Automate secure VM deployments by adding encryption to ARM templates</span></span>
metadata:
  title: <span data-ttu-id="0e274-102">Esercizio - Automatizzare le distribuzioni di VM sicure aggiungendo la crittografia ai modelli di Azure Resource Manager</span><span class="sxs-lookup"><span data-stu-id="0e274-102">Exercise - Automate secure VM deployments by adding encryption to ARM templates</span></span>
  description: <span data-ttu-id="0e274-103">Esercizio - Automatizzare le distribuzioni di VM sicure aggiungendo la crittografia ai modelli di Azure Resource Manager</span><span class="sxs-lookup"><span data-stu-id="0e274-103">Exercise - Automate secure VM deployments by adding encryption to ARM templates</span></span>
  ms.openlocfilehash: 949e0b7a3704f407bd821dd5253fc3ee2162b866
  ms.sourcegitcommit: b97ed72bd7e3fb77b49de71e8ef35d3f70dfd636
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43789486"
durationInMinutes: 10
content: '[!include[](includes/6-exercise-automate-secure-vm-deployments-using-arm-templates.md)]'
