### YamlMime:ModuleUnit
uid: learn.store-app-data-with-azure-blob-storage.5-configure-and-initialize-the-client-library
title: Configurare e inizializzare la libreria client
metadata:
  title: Configurare e inizializzare la libreria client
  description: Configurare e inizializzare la libreria client
  ms.openlocfilehash: c7cc43321a9dc94f71e7689a47ca31e8fe7c774c
  ms.sourcegitcommit: 12b4711682dac42f742a944fd9baa0e9dd09cf35
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 08/22/2018
  ms.locfileid: "40440420"
durationInMinutes: 10
interactive: bash-editor
content: '[!include[](includes/5-configure-and-initialize-the-client-library.md)]'
