### YamlMime:ModuleUnit
uid: learn.store-app-data-with-azure-blob-storage.5-configure-and-initialize-the-client-library
title: Configurare e inizializzare la libreria client
metadata:
  title: Configurare e inizializzare la libreria client
  description: Configurare e inizializzare la libreria client
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: bedd297c48ead2c2aadba57e57e3bb8b965344fb
  ms.sourcegitcommit: 8213d1af6ad9da967a5e195f0b40b00265cb192c
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/10/2018
  ms.locfileid: "44307519"
durationInMinutes: 10
interactive: bash-editor
azureSandbox: true
content: '[!include[](includes/5-configure-and-initialize-the-client-library.md)]'
