### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.1-create-azure-iot-central-application
title: <span data-ttu-id="619c1-101">Creare un'applicazione Azure IoT Central</span><span class="sxs-lookup"><span data-stu-id="619c1-101">Create an Azure IoT Central application</span></span>
metadata:
  title: <span data-ttu-id="619c1-102">Creare un'applicazione Azure IoT Central</span><span class="sxs-lookup"><span data-stu-id="619c1-102">Create an Azure IoT Central application</span></span>
  description: <span data-ttu-id="619c1-103">Creare un'applicazione Azure IoT Central</span><span class="sxs-lookup"><span data-stu-id="619c1-103">Create an Azure IoT Central application</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 98e9a83d594bc3611f3048909b7d238ea289901e
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47137825"
durationInMinutes: 5
content: '[!include[](includes/1-create-azure-iot-central-application.md)]'
