### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.3-connect-your-application-to-simulator
title: Nel computer di caffè simulati di connettersi all'applicazione
metadata:
  title: Nel computer di caffè simulati di connettersi all'applicazione
  description: Nel computer di caffè simulati di connettersi all'applicazione
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 5
content: |
  [!include[](includes/3-connect-your-application-to-simulator.md)]