### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.5-configure-rules-and-actions
title: <span data-ttu-id="8a64c-101">Configurare le regole e le azioni per il monitoraggio della macchina da caffè</span><span class="sxs-lookup"><span data-stu-id="8a64c-101">Configure rules and actions to monitor your coffee machine</span></span>
metadata:
  title: <span data-ttu-id="8a64c-102">Configurare le regole e le azioni per il monitoraggio della macchina da caffè</span><span class="sxs-lookup"><span data-stu-id="8a64c-102">Configure rules and actions to monitor your coffee machine</span></span>
  description: <span data-ttu-id="8a64c-103">Configurare le regole e le azioni per il monitoraggio della macchina da caffè</span><span class="sxs-lookup"><span data-stu-id="8a64c-103">Configure rules and actions to monitor your coffee machine</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 5a6343fe6bbbe47ec15d343ce3e448315a27f606
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47138052"
durationInMinutes: 12
content: '[!include[](includes/5-configure-rules-and-actions.md)]'
