### YamlMime:ModuleUnit
uid: learn.enable-reliable-messaging-for-big-data-applications-using-azure-event-hubs.4-configure-applications-to-send-or-receive-messages-through-an-event-hub
title: Configurare le applicazioni per l'invio o la ricezione dei messaggi tramite un hub eventi
metadata:
  title: Configurare le applicazioni per l'invio o la ricezione dei messaggi tramite un hub eventi
  description: Configurare le applicazioni per l'invio o la ricezione dei messaggi tramite un hub eventi
  ms.openlocfilehash: e52c36959360c571ac76dc9906aa6c26be2ab487
  ms.sourcegitcommit: e364b61d89b547c49e271e6d168801011f7f4733
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 08/26/2018
  ms.locfileid: "42936757"
durationInMinutes: 5
content: '[!include[](includes/4-configure-applications-to-send-or-receive-messages-through-an-event-hub.md)]'
