### YamlMime:ModuleUnit
uid: learn.enable-reliable-messaging-for-big-data-applications-using-azure-event-hubs.5-exercise-configure-applications-to-send-or-receive-messages-through-an-event-hub
title: <span data-ttu-id="67144-101">Configurare le applicazioni per l'invio o la ricezione dei messaggi tramite un hub eventi</span><span class="sxs-lookup"><span data-stu-id="67144-101">Configure applications to send or receive messages through an Event Hub</span></span>
metadata:
  title: <span data-ttu-id="67144-102">Configurare le applicazioni per l'invio o la ricezione dei messaggi tramite un hub eventi</span><span class="sxs-lookup"><span data-stu-id="67144-102">Configure applications to send or receive messages through an Event Hub</span></span>
  description: <span data-ttu-id="67144-103">Configurare le applicazioni per l'invio o la ricezione dei messaggi tramite un hub eventi</span><span class="sxs-lookup"><span data-stu-id="67144-103">Configure applications to send or receive messages through an Event Hub</span></span>
  ms.openlocfilehash: 28d21d21388a71eea65893daeb7f6d2a374c8e64
  ms.sourcegitcommit: b1b68b477ab39109c48f227b504a5050cae7a718
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/01/2018
  ms.locfileid: "43410749"
durationInMinutes: 10
content: '[!include[](includes/5-exercise-configure-applications-to-send-or-receive-messages-through-an-event-hub.md)]'
