### YamlMime:ModuleUnit
uid: learn.make-your-virtual-machines-highly-available.5-exercise-configure-a-load-balancer-in-azure
title: 'Esercizio: configurare un bilanciamento del carico in Azure'
metadata:
  title: 'Esercizio: configurare un bilanciamento del carico in Azure'
  description: 'Esercizio: configurare un bilanciamento del carico in Azure'
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 20
content: |
  [!include[](includes/5-exercise-configure-a-load-balancer-in-azure.md)]