### YamlMime:ModuleUnit
uid: learn.design-a-great-azure-architecture.3-design-for-security
title: Progettare per la sicurezza
metadata:
  title: Progettare per la sicurezza
  description: Progettare per la sicurezza
  ms.openlocfilehash: 394af78966bfde3b2c82e2af17a10bb8680fc659
  ms.sourcegitcommit: 09425147d998035edf9d2d36006a54d85e3cf75d
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/06/2018
  ms.locfileid: "43847249"
durationInMinutes: 10
content: >
  [!include[](includes/3-design-for-security.md)]
quiz:
  title: 'Verifica delle conoscenze: Progettare per la sicurezza'
  questions:
  - content: A quali dei tipi seguenti di dati può essere necessario applicare misure di protezione per la sicurezza?
    choices:
    - content: Dati dei clienti che contengono informazioni personali
      isCorrect: false
      incorrectExplanation: Benché sia importante applicare misure di protezione per la sicurezza appropriate a questi dati, questa non è l'unica scelta corretta.
    - content: Dati finanziari a supporto delle operazioni aziendali
      isCorrect: false
      incorrectExplanation: Benché sia importante applicare misure di protezione per la sicurezza appropriate a questi dati, questa non è l'unica scelta corretta.
    - content: Dati contenenti proprietà intellettuale
      isCorrect: false
      incorrectExplanation: Benché sia importante applicare misure di protezione per la sicurezza appropriate a questi dati, questa non è l'unica scelta corretta.
    - content: A tutti i tipi di dati indicati sopra può essere necessario applicare misure di protezione per la sicurezza
      isCorrect: true
      correctExplanation: Tutti i tipi di dati indicati sopra possono meritare misure di protezione per la sicurezza aggiuntive.
  - content: Quale tra i seguenti è un esempio di attacco che è possibile riscontrare nel livello perimetrale?
    choices:
    - content: Credenziali esposte pubblicate online
      isCorrect: false
      incorrectExplanation: Le credenziali esposte pongono un rischio elevato per un'organizzazione, ma non costituiscono un attacco del livello perimetrale.
    - content: Attacco flood SYN
      isCorrect: true
      correctExplanation: Gli attacchi flood SYN sono un tipo di attacco Denial of Service osservato comunemente nella rete perimetrale.
    - content: Progettazione di ingressi per penetrare nel data center
      isCorrect: false
      incorrectExplanation: La progettazione di ingressi è un attacco del livello fisico.
    - content: Ransomware per la crittografia dei dischi di una macchina virtuale
      isCorrect: false
      incorrectExplanation: Gli attacchi tramite ransomware sono attacchi del livello di calcolo/della macchina virtuale.
