### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-web-apps.5-exercise-create-an-asp.net-core-web-application-on-linux
title: "Esercizio: Creare un'applicazione ASP.NET Core in Linux"
metadata:
  title: "Esercizio: Creare un'applicazione ASP.NET Core in Linux"
  description: "Esercizio: Creare un'applicazione ASP.NET Core in Linux"
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: d568d2d92f827fea2713d8c79f29fc646033d588
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44234955"
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-an-asp.net-core-web-application-on-linux.md)]'
