### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-app-service.5-exercise-create-an-asp.net-core-web-application-on-linux
title: "Esercizio: Creare un'applicazione ASP.NET Core in Linux"
metadata:
  title: "Esercizio: Creare un'applicazione ASP.NET Core in Linux"
  description: "Esercizio: Creare un'applicazione ASP.NET Core in Linux"
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 3c73c9ee2da417fcbfb91cc5beeae6a13659c5e7
  ms.sourcegitcommit: 8fbdc9990a51065cb16b1ff4644ca3af93798a5e
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/14/2018
  ms.locfileid: "45586312"
interactive: bash
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-an-asp.net-core-web-application-on-linux.md)]'
