### YamlMime:ModuleUnit
uid: learn.design-for-performance-and-scalability.5-identify-performance-bottlenecks-in-your-application
title: <span data-ttu-id="85ee0-101">Identificare i colli di bottiglia relativi alle prestazioni nell'applicazione</span><span class="sxs-lookup"><span data-stu-id="85ee0-101">Identify performance bottlenecks in your application</span></span>
metadata:
  title: <span data-ttu-id="85ee0-102">Identificare i colli di bottiglia relativi alle prestazioni nell'applicazione</span><span class="sxs-lookup"><span data-stu-id="85ee0-102">Identify performance bottlenecks in your application</span></span>
  description: <span data-ttu-id="85ee0-103">In questa unità viene spiegato come identificare i colli di bottiglia relativi alle prestazioni nell'applicazione</span><span class="sxs-lookup"><span data-stu-id="85ee0-103">In this unit we'll discuss how to identify performance bottlenecks in your application</span></span>
  ms.openlocfilehash: 0b5ab3a983a4b3dfc3a76c914b6a565f3ee7ed2c
  ms.sourcegitcommit: 926510a198d738c5726081f6d7994fe9b6fc6edb
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 08/29/2018
  ms.locfileid: "43181186"
durationInMinutes: 5
content: >
  [!include[](includes/5-identify-performance-bottlenecks-in-your-application.md)]
quiz:
  title: "<span data-ttu-id=\"85ee0-104\">Verifica delle conoscenze: identificare i colli di bottiglia relativi alle prestazioni nell'applicazione</span><span class=\"sxs-lookup\"><span data-stu-id=\"85ee0-104\">Knowledge Check - Identify performance bottlenecks in your application</span></span>"
  questions:
  - content: <span data-ttu-id="85ee0-105">Quale delle seguenti affermazioni meglio descrive Application Insights?</span><span class="sxs-lookup"><span data-stu-id="85ee0-105">Which of the following best describes Application Insights?</span></span>
    choices:
    - content: <span data-ttu-id="85ee0-106">Un'unica console per le esigenze di monitoraggio in Azure</span><span class="sxs-lookup"><span data-stu-id="85ee0-106">A single pane of glass for our monitoring needs in Azure</span></span>
      isCorrect: false
    - content: <span data-ttu-id="85ee0-107">Un'implementazione del modello di monitoraggio dell'integrità dell'endpoint</span><span class="sxs-lookup"><span data-stu-id="85ee0-107">An implementation of the health endpoint monitoring pattern</span></span>
      isCorrect: false
    - content: <span data-ttu-id="85ee0-108">Un'area di lavoro per abilitare la raccolta dei log tra applicazioni e infrastruttura</span><span class="sxs-lookup"><span data-stu-id="85ee0-108">A workspace to enable collection of logs across infrastructure and applications</span></span>
      isCorrect: false
    - content: <span data-ttu-id="85ee0-109">Un servizio per monitorare la disponibilità, le prestazioni e l'uso delle applicazioni Web</span><span class="sxs-lookup"><span data-stu-id="85ee0-109">A service to monitor availability, performance, and usage of web applications</span></span>
      isCorrect: true
  - content: <span data-ttu-id="85ee0-110">È possibile usare Log Analytics per tenere traccia delle metriche e dei log personalizzati.</span><span class="sxs-lookup"><span data-stu-id="85ee0-110">You can use Log Analytics to track custom logs and metrics.</span></span>
    choices:
    - content: <span data-ttu-id="85ee0-111">Vero</span><span class="sxs-lookup"><span data-stu-id="85ee0-111">True</span></span>
      isCorrect: true
    - content: <span data-ttu-id="85ee0-112">Falso</span><span class="sxs-lookup"><span data-stu-id="85ee0-112">False</span></span>
      isCorrect: false
